import type { CapacitorConfig } from "@capacitor/cli";

// Meridiano Matemática is a server-rendered Next.js app (dynamic routes,
// server actions, streaming) — it isn't statically exported, so it can't
// ship as bundled web assets the way a static SPA would with Capacitor.
// Instead this points the native shell at the hosted deployment
// (NEXT_PUBLIC_SITE_URL, the same canonical URL src/lib/siteUrl.ts uses
// for metadata) via `server.url`, the standard Capacitor pattern for
// wrapping a remote web app. See docs/mobile-app.md for what's actually
// needed to turn this into an installable iOS/Android build — this repo
// only carries the config, not `ios/`/`android/` platform projects
// (those are generated by `npx cap add`, which needs Xcode/Android
// Studio, on a machine that has them).
const config: CapacitorConfig = {
  appId: "com.meridianomatematica.app",
  appName: "Meridiano Matemática",
  webDir: "public",
  server: {
    url: process.env.NEXT_PUBLIC_SITE_URL || "https://meridiano-math.example.com",
    cleartext: false,
  },
};

export default config;
